import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import sqlite3
import json
import textwrap
import re
from io import StringIO, BytesIO

import ollama

st.set_page_config(page_title="AI Data Analyst Agent", layout="wide")

st.title("🤖 AI Data Analyst Agent (Ollama + Streamlit)")
st.write(
    "Upload a CSV and ask questions in natural language. "
    "The AI will generate SQL (when needed), run it, plot charts (only if needed), "
    "and explain insights."
)

# -----------------------------------------------------------------------------------
# Helper: Load CSV
# -----------------------------------------------------------------------------------
@st.cache_data
def load_csv(file):
    return pd.read_csv(file)

# -----------------------------------------------------------------------------------
# Helper: Fix column names inside SQL automatically
# -----------------------------------------------------------------------------------
def fix_sql_column_names(sql: str, df: pd.DataFrame) -> str:
    """
    Fixes wrong column names generated by the model.
    Example: model outputs Annual_Income_k$ but real column is Annual Income (k$)
    """
    if not sql:
        return sql

    fixed_sql = sql
    real_cols = df.columns.tolist()

    tokens = re.findall(r"[A-Za-z0-9_]+", sql)

    for real in real_cols:
        clean_real = re.sub(r"[^a-zA-Z0-9]", "", real).lower()

        for t in tokens:
            clean_t = re.sub(r"[^a-zA-Z0-9]", "", t).lower()

            if clean_real == clean_t:
                fixed_sql = re.sub(rf"\b{t}\b", f'"{real}"', fixed_sql)

    return fixed_sql

# -----------------------------------------------------------------------------------
# Helper: Build LLM Prompt
# -----------------------------------------------------------------------------------
def build_analysis_prompt(df: pd.DataFrame, question: str, max_rows: int = 5) -> str:
    schema = "\n".join([f"- {col} ({dtype})" for col, dtype in df.dtypes.items()])
    sample = df.head(max_rows).to_csv(index=False)

    prompt = f"""
You are an expert data analyst.

You are given:
1. A table named `data` with columns:
{schema}

2. A small sample of the data in CSV:
{sample}

Your task:
- Understand the user's question.
- Generate a SQL query **only if needed**.
- Generate a chart specification **only if helpful**.
- Otherwise set "sql": null or chart.type="none".
- Provide clear insights.

Return ONLY JSON:
{{
  "sql": "SQL query here or null",
  "chart": {{
    "type": "bar/line/scatter/histogram/none",
    "x": "column_name_or_null",
    "y": "column_name_or_null"
  }},
  "insight": "Your explanation here"
}}

User question: {question}
"""
    return textwrap.dedent(prompt)

# -----------------------------------------------------------------------------------
# Helper: Talk to Ollama
# -----------------------------------------------------------------------------------
def call_ollama(prompt: str, model: str):
    response = ollama.chat(
        model=model,
        messages=[{"role": "user", "content": prompt}],
    )
    return response["message"]["content"]

# -----------------------------------------------------------------------------------
# Execute SQL
# -----------------------------------------------------------------------------------
def execute_sql(df: pd.DataFrame, sql: str):
    conn = sqlite3.connect(":memory:")
    df.to_sql("data", conn, index=False, if_exists="replace")
    try:
        result = pd.read_sql_query(sql, conn)
    finally:
        conn.close()
    return result

# -----------------------------------------------------------------------------------
# Plot Chart (Fixed for numeric x-values)
# -----------------------------------------------------------------------------------
def plot_chart(df: pd.DataFrame, chart_spec: dict):
    chart_type = (chart_spec.get("type") or "none").lower()
    x_col = chart_spec.get("x")
    y_col = chart_spec.get("y")

    if chart_type == "none":
        return None

    if not x_col or not y_col:
        st.error("Chart specification missing x or y.")
        return None
    
    if x_col not in df.columns or y_col not in df.columns:
        st.error(f"Chart columns not found: x={x_col}, y={y_col}")
        return None

    fig, ax = plt.subplots()

    # FIX — ensure x-values are strings in bar charts
    if chart_type == "bar":
        if pd.api.types.is_numeric_dtype(df[x_col]) or pd.api.types.is_datetime64_any_dtype(df[x_col]):
            x_vals = df[x_col].astype(str)
        else:
            x_vals = df[x_col]
        ax.bar(x_vals, df[y_col])

    elif chart_type == "line":
        ax.plot(df[x_col], df[y_col])

    elif chart_type == "scatter":
        ax.scatter(df[x_col], df[y_col])

    elif chart_type == "histogram":
        ax.hist(df[y_col])

    ax.set_xlabel(x_col)
    ax.set_ylabel(y_col)
    ax.set_title(f"{chart_type.capitalize()} of {y_col} vs {x_col}")

    st.pyplot(fig)
    return fig

# -----------------------------------------------------------------------------------
# UI — File Upload
# -----------------------------------------------------------------------------------
uploaded = st.sidebar.file_uploader("📂 Upload a CSV file", type=["csv"])
model_name = st.sidebar.text_input("Ollama model name", value="mistral")

if uploaded is None:
    st.info("Upload a CSV file to start.")
    st.stop()

df = load_csv(uploaded)

# -----------------------------------------------------------------------------------
# Preview
# -----------------------------------------------------------------------------------
st.subheader("Preview of Data")
st.dataframe(df.head())

st.subheader("Columns and Types")
st.write(df.dtypes.astype(str))

# -----------------------------------------------------------------------------------
# Ask Question
# -----------------------------------------------------------------------------------
st.subheader("Ask a Question")
question = st.text_area("Ask something like: 'What is the average Sales by Country?'", height=100)

if st.button("🔍 Analyze"):
    if not question.strip():
        st.warning("Enter a question first.")
        st.stop()

    with st.spinner("Thinking..."):
        prompt = build_analysis_prompt(df, question)
        raw = call_ollama(prompt, model_name)

    st.subheader("Raw Model Response")
    st.code(raw, language="json")

    # Parse JSON
    try:
        parsed = raw.strip()
        if parsed.startswith("```"):
            parsed = parsed.split("```json")[-1]
            parsed = parsed.split("```")[0]
        result = json.loads(parsed)
    except:
        st.error("Model did not return valid JSON.")
        st.stop()

    sql = result.get("sql")
    chart_spec = result.get("chart")
    insight = result.get("insight")

    # -----------------------------------------------------------------------------------
    # Fix SQL (auto-correct column names)
    # -----------------------------------------------------------------------------------
    if sql:
        sql = fix_sql_column_names(sql, df)

    # -----------------------------------------------------------------------------------
    # Insights
    # -----------------------------------------------------------------------------------
    st.subheader("📘 Insights")
    st.write(insight)

    # -----------------------------------------------------------------------------------
    # Run SQL only if valid
    # -----------------------------------------------------------------------------------
    sql_result = None

    if sql and isinstance(sql, str):
        st.subheader("🧮 SQL Query")
        st.code(sql, language="sql")

        try:
            sql_result = execute_sql(df, sql)
            st.subheader("📊 SQL Result")
            st.dataframe(sql_result)
        except Exception as e:
            st.error(f"SQL Error: {e}")

    # -----------------------------------------------------------------------------------
    # Chart (ONLY if AI requests it)
    # -----------------------------------------------------------------------------------
    st.subheader("📈 Chart")

    if chart_spec and chart_spec.get("type") != "none":
        chart_df = sql_result if sql_result is not None else df
        fig = plot_chart(chart_df, chart_spec)
    else:
        st.info("No chart required for this query.")

